services:
  - type: web
    name: skyblue-festive-moments
    env: python
    plan: free # or starter/pro, depending on your needs
    region: oregon # change if you prefer another Render region
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app1:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
